name: build adocs

on:
  push:
    branches:
    - develop
    paths:
    - docs

jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: asciidoctor build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build html
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"
    - name: Build pdf
      id: adocbuild_pdf
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor-pdf -D docs -o document.pdf -a lang=nb docs/main.adoc"
      continue-on-error: true
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
