name: build adocs and publish v1.1 to production

on:
  push:
    branches:
      - v1.1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: v1.1

      - name: Build html
        id: adocbuild
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"

      - name: Build pdf
        id: adocbuild_pdf
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf -D docs -o files/dcat-ap-no.pdf -a lang=nb docs/main.adoc"
        continue-on-error: true

      - name: Upload rdf to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
        id: upload-rdf
        with:
          ontology-type: "specification"
          ontology: "dcat-ap-no"
          version: "v1.1"
          host: "https://fellesdatakatalog.digdir.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          files: |
            docs/index.html text/html nb
            docs/files/dcat-ap-no.pdf application/pdf nb files/dcat-ap-no.pdf
            docs/files/dcat-ap-no-1.1p2.uxf text/xml nb files/dcat-ap-no-1.1p2.uxf
            docs/files/dcat-ap-no-1.1p3.png image/png nb files/dcat-ap-no-1.1p3.png
            docs/images/dcat-ap-no-1-1-diagram.png image/png nb images/dcat-ap-no-1-1-diagram.png
            docs/images/dcat-ap-no-1.1p3.png image/png nb images/dcat-ap-no-1.1p3.png
